### ISSUE TITLE
Seek doesn't work after upgrade to 0.4.7

### ISSUE THREAD

**Issue by nelson777** [clappr/clappr#2060]
(Please change label to bug. I wrongly select question tag)

Seek function is broken after upgrading to v0.4.7 from version 0.3.13. I had this working for sometime in production. When I tried to update the lib seek function didn't work anymore.

I tryied with seek and seekPercentage. I always get the same error:

```
ERROR DOMException: Failed to execute 'start' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0).
    at HTML5Video.seek (https://localhostassiste:4200/vendor.js:8877:34)
    at Container.seek (https://localhostassiste:4200/vendor.js:5801:23)
    at Container.seekPercentage (https://localhostassiste:4200/vendor.js:5820:16)
    at Player.seekPercentage (https://localhostassiste:4200/vendor.js:7946:35)
    at VideoAtualComponent.ativarPlayer (https://localhostassiste:4200/main.js:13860:35)
    at Object.next (https://localhostassiste:4200/main.js:13791:26)
    at ConsumerObserver.next (https://localhostassiste:4200/vendor.js:101430:33)
    at SafeSubscriber._next (https://localhostassiste:4200/vendor.js:101399:26)
    at SafeSubscriber.next (https://localhostassiste:4200/vendor.js:101370:18)
    at https://localhostassiste:4200/vendor.js:103099:24
```

Did I forget something in the upgrade ? getDuration() is fine, getCurrentTime() also. Checked values all ok. The video I'm trying to seek is 1162 secs long. Even with a fixed value of 500 I get the same error.

I found this workaround:
```
let videoTag = (<HTMLVideoElement>document.querySelector("video"));
if (videoTag)
	videoTag.currentTime = this.video.lastPointSeen;
```

But I much rather use seek function. What am I doing wrong ?

**Comment by nelson777** [comment]
Please change to bug. I wrongly select question tag.

**Comment by leaofelipe** [comment]
Issue closed due to inactivity.
