### ISSUE TITLE
New version of Clappr is not working with RTMP plugin

### ISSUE THREAD

**Issue by tarkanlar** [clappr/clappr#517]
I got this error with the latest version of Clappr. Older version working properly
```[error][t] error on event o5:progress trigger - TypeError: this.el.getBytesLoaded is not a function
    at t.n.progress.value (http://localhost:3333/dist/clappr.min.js:3:15261)
    at h (http://localhost:3333/dist/clappr.min.js:5:28729)
    at t.n.trigger.value (http://localhost:3333/dist/clappr.min.js:5:28003)
    at Function.o.trigger (http://localhost:3333/dist/clappr.min.js:6:5518)
    at <anonymous>:1:38```

**Comment by flavioribeiro** [comment]
hey @tarkanlar can you open this issue directly on plugin's repo? [https://github.com/clappr/clappr-rtmp-plugin](https://github.com/clappr/clappr-rtmp-plugin)
