### ISSUE TITLE
Broken hls.js import

### ISSUE THREAD

**Issue by leandromoreira** [clappr/clappr#831]
We updated to the latest version of hls.js and we were about to release a new version but we can't run tests or the player itself.

```
ERROR in ./~/hls.js/index.js
Module build failed: ReferenceError: [BABEL] /Users/leandro/src/clappr/node_modules/hls.js/index.js: Unknown option: /Users/leandro/src/clappr/node_modules/hls.js/.babelrc.presets
    at Logger.error (/Users/leandro/src/clappr/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/leandro/src/clappr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/leandro/src/clappr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/leandro/src/clappr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/leandro/src/clappr/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/leandro/src/clappr/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/leandro/src/clappr/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/leandro/src/clappr/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/leandro/src/clappr/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/leandro/src/clappr/node_modules/babel-loader/index.js:71:12)
 @ ./src/playbacks/hls/hls.js 9:5693-5710
```

**Comment by leandromoreira** [comment]
https://github.com/dailymotion/hls.js/issues/240

**Comment by leandromoreira** [comment]
Ne wee to fix this to release the new version.

**Comment by jlmcdonald** [comment]
@leandromoreira I just did this myself last night on a local copy of this repo ... the "presets" option is only available in Babel 6.x, so it will require updating Babel (and possibly updating places where Babel is required in the Clappr code)

**Comment by leandromoreira** [comment]
thanks @jlmcdonald :)

**Comment by leandromoreira** [comment]
It is not so straightforward and easy as I thought it'd be:

At first I tried to update babel:
```diff
-    "babel-core": "^5.8.23",
-    "babel-loader": "^5.3.2",
+    "babel-core": "^6.5.1",
+    "babel-loader": "^6.2.2",
+    "babel-preset-es2015": "^6.5.0",

     loaders: [
       {
         test: /\.js$/,
-        loader: 'babel',
+        loader: 'babel-loader',
+        query: { presets: ['es2015'] }
       },
```

But then I started to receive some strange errors while `npm tests`

```
  Uncaught TypeError: Super expression must either be null or a function, not object
  at /Users/leandro/src/clappr/test/components/loader_spec.js:4797
```

And [I'm trying some stuffs](https://www.google.com.br/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Uncaught+TypeError%3A+Super+expression+must+either+be+null+or+a+function%2C+not+object) but none of them have worked until now.

**Comment by jlmcdonald** [comment]
Yeah ... Babel 6 loaders require a bit different way to handle extending of imported classes; to avoid needing to rewrite a lot of it, though, there's the plugin "babel-plugin-add-module-exports" -- installing it and initializing it via .babelrc in main folder will allow Babel 6 to handle the same syntax that Babel 5 did. I just submitted a pull request that provides all the necessary changes (it successfully passes all tests and builds a new deployment)

**Comment by leandromoreira** [comment]
thanks @jlmcdonald lol

**Comment by leandromoreira** [comment]
https://github.com/clappr/clappr/commit/393c61afa258f34eb36153a9c4cbebc7495d21cc
